### ISSUE TITLE
Customer Segmentation Examples

### ISSUE THREAD

**Issue by shouvik19** [datensolutions/zenhub#2]
As a data scientist, I will look at better examples of customer segmentation.

**Comment by shouvik19** [comment]
I have found three comprehensive examples:-

1. Netflix
2. Coke
3. Walmart.

Please find the attached document that specifies these tasks

[https://app.zenhub.com/files/329769892/848cd7df-2c41-4899-aa03-84dce068cd5d/download](https://app.zenhub.com/files/329769892/848cd7df-2c41-4899-aa03-84dce068cd5d/download)

**Comment by shouvik19** [comment]
Added Netflix and coke examples to the deck.
[Uploading... instacart_customer_segmentation_0118_v2.pptx]

**Comment by shouvik-daten** [comment]
Netflix Example Summary:

1) Netflix

- Netflix uses customer segmentation to identify the pulse of its audience.
- For a study conducted on the viewers of a social drama genre, they filtered their customer database to have users who have watched the social drama  
- On the filtered customer database, we apply customer segmentation using k-means clustering.
- For the premium social-drama viewers, we see that they like Kevin spacey movies and also the movies directed by David Fincher.
- Hence Netflix decided to create a social drama TV show, starring kevin spacey and David fincher as the director.
